### ISSUE TITLE
PropTypes via the main React package is now deprecated

### ISSUE THREAD

**Issue by marclaliberte** [cht8687/react-hover#10]
Using PropTypes via the main React package is deprecated. Instead, import the prop-types package from npm. Affects ReactHover.js, lib/Hover.js and lib/Trigger.js.

**Console Warning:** Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by cht8687** [comment]
thanks. @marclaliberte

**Comment by cht8687** [comment]
fixed in [](url)https://github.com/cht8687/react-hover/releases/tag/1.1.0
