### ISSUE TITLE
Flickering when using hover as overlay container

### ISSUE THREAD

**Issue by davidfells** [cht8687/react-hover#21]
I'm positioning the hover element so it sits in the center of the trigger element. Hover element contains links. When the trigger element is underneath the hover element, and you put your cursor over the hover element, the hover element constantly flickers.

**Comment by cht8687** [comment]
yes, this is currently an issue. I recommend adding some `shiftX` and `shiftY` to the hover element before we have a solution for this.

**Comment by cht8687** [comment]
@davidfells 
I think this [#30](https://github.com/cht8687/react-hover/pull/30) will fix this issue.

**Comment by cht8687** [comment]
@davidfells  I've released a new version to address this issue.
