### ISSUE TITLE
Add IE9, IE10 support

### ISSUE THREAD

**Issue by cht8687** [cht8687/react-hover#6]
reported by @Laurence-infotrack...

**Comment by rui-infotrack** [comment]
Why there hasn't been any work on this issue??? Is this project still being maintained?

**Comment by cht8687** [comment]
@rui-infotrack 

 I am writing the V2 and currently in progress. I am going to push WIP code to a separate branch.
( Life being so busy for me these days, I am spending most of my spare time with my GF : ) )

**Comment by cht8687** [comment]
@rui-infotrack 

I am trying to get children's function name in [here](https://github.com/cht8687/react-hover/blob/feature/version2.0/src/ReactHover.js#L34-L40), but seems doesn't work really well.

: (

**Comment by rui-infotrack** [comment]
Come on, Laurence needs this fix, lol!
Object.assign is not understood by IE. I think we can add a utility method like `extend` or sth like that. Currently you're assuming it's ES6 environment...

Heard V2 is going on... is it still in beta?

**Comment by cht8687** [comment]
I hope [this](https://github.com/cht8687/react-hover/commit/9f29830c67be661a7465785b6d55c131276559ef) fixed the issue. Let me know if error still occur. 😄

**Comment by Laurence-infotrack** [comment]
all good now

**Comment by cht8687** [comment]
@Laurence-infotrack :+1:
